[package]
name = "toky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9"
solana-program = "=1.9.1"
thiserror = "1.0"

[features]
no-entrypoint = []